name: mbank
description: "Нэвтрэх, бүртгүүлэх үйлдэлтэй апп."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.0
  flutter_otp_text_field: ^1.5.1+1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/